name: cwc_cryptic_crusade
description: "CWC Cryptic Crusade Event App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  card_swiper: ^3.0.1
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_animated_loadingkit: ^0.0.7
  flutter_bloc: ^8.1.6
  flutter_expandable_fab: ^2.3.0
  fpdart: ^1.1.0
  get_it: ^8.0.0
  go_router: ^14.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SpaceMono
      fonts:
        - asset: assets/font/SpaceMono-Regular.ttf
          weight: 400
        - asset: assets/font/SpaceMono-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/font/SpaceMono-Bold.ttf
          weight: 700
        - asset: assets/font/SpaceMono-BoldItalic.ttf
          weight: 700
          style: italic
        
